### ISSUE TITLE
专业术语

### ISSUE THREAD

**Issue by zisheng-ai** [youngjuning/vscode-api-cn#27]
这里沉淀一些关于这个仓库翻译的专业术语。

- active editor：活动编辑器
- active terminal：活动命令行
- authentication session：认证会话
- comment：评论
- controller：控制器
- extension：扩展
- namespace：命名空间
- Namespace for dealing with xxx：用于处理 xxx 的命名空间
- provider：提供者
- reaction：响应
- source control：源代码管理程序
- thread：线程

**Comment by zisheng-ai** [comment]
- [x] active editor：活动编辑器
- [x] active terminal：活动命令行
- [x] authentication session：认证会话
- [x] extension：扩展
- [x] namespace：命名空间
- [x] Namespace for dealing with xxx：用于处理 xxx 的命名空间
- [x] provider：提供者
- [x] source control：源代码管理程序

**Comment by yangyang825** [comment]
- [x] comment：评论
- [x] controller：控制器
- [x] reaction：响应
- [x] thread：线程
