### ISSUE TITLE
add contributos

### ISSUE THREAD

**Issue by zisheng-ai** [youngjuning/vscode-api-cn#4]

**Comment by zisheng-ai** [comment]
@all-contributors please add @youngjuning for infra, maintenance, translation, doc, ideas, design, code

**Comment by zisheng-ai** [comment]
@all-contributors please add @youngjuning for infra, maintenance, translation, doc, ideas, design, code

**Comment by zisheng-ai** [comment]
@all-contributors please add @youngjuning for infra, maintenance, translation, doc, ideas, design, code

**Comment by zisheng-ai** [comment]
@all-contributors please add @youngjuning for code

**Comment by zisheng-ai** [comment]
@all-contributors please add @Saber2pr for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add @gepingli for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add Imchenlong for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add pan463859 for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add @Saber2pr for ideas

**Comment by youngjuning** [comment]
@all-contributors please add @Tecvan-fe for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add @Tecvan-fe for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add @sherry-zxy for translation

**Comment by youngjuning** [comment]
@all-contributors please add @liuqh0609 for translation

**Comment by youngjuning** [comment]
@all-contributors please add @liuqh0609 for translation

**Comment by youngjuning** [comment]
@all-contributors please add @yangyang0825 for translation

**Comment by youngjuning** [comment]
@all-contributors please add @yangyang0825 for translation

**Comment by youngjuning** [comment]
@all-contributors please add @yangyang0825 for translation

**Comment by zisheng-ai** [comment]
@all-contributors please add @yangyang0825 for translation
